### ISSUE TITLE
It would be great to be able to configure a max width of the console output

### ISSUE THREAD

**Issue by escamoteur** [serilog/serilog-sinks-coloredconsole#1]
Hi,

I don't know, perhaps this is already possible, but if I Log a complex Object the line gets so long that it is broken to the next line and the output is not very readable.
Would be great if I could set a max width and that the the output is wrapped in a way that makes sense like:

2016-05-13 13:11:08 [Verbose] REQUEST "http://localhost:3579/sync/syncstate"
2016-05-13 13:11:08 [Verbose] REQUEST "http://localhost:3579/sync/day"
2016-05-13 13:11:08 [Verbose] SyncEvent: UserId: "78eb5882-07f5-43b1-8eea-d11f9beea428" -
                                                  Dayfrom Device: 
                                                       QmdSyncDay 
                                                               { LastModified: 05/13/2016 11:11:08,
                                                                  DateOfDay: 05/12/2016 22:00:00,  
                                                                  Quote: ""
                                                               } - 
                                                      DayOnServer: null
2016-05-13 13:11:08 [Verbose] REQUEST "http://localhost:3579/sync/syncstate"

Or something like that.
Cheers
THomas

**Comment by merbla** [comment]
@escamoteur have you had a look at https://github.com/serilog/serilog-sinks-literate

**Comment by escamoteur** [comment]
I tried literate Console, but hat's not what I meant. I'm talking about wrapping and indentation. Sorry when I post above was not really good formated. I try it again:

```
2016-05-13 13:11:08 [Verbose] REQUEST "http://localhost:3579/sync/syncstate"
2016-05-13 13:11:08 [Verbose] REQUEST "http://localhost:3579/sync/day"
2016-05-13 13:11:08 [Verbose] SyncEvent: UserId: "78eb5882-07f5-43b1-8eea-d11f9beea428" - 
   Dayfrom Device: 
    QmdSyncDay 
   {
        LastModified: 05/13/2016 11:11:08,
        DateOfDay: 05/12/2016 22:00:00,
        Quote: ""
    }  
    DayOnServer: null
2016-05-13 13:11:08 [Verbose] REQUEST "http://localhost:3579/sync/syncstate"
```

Cheers

**Comment by nblumhardt** [comment]
@escamoteur it's an interesting suggestion :-)

It'd be a (really quite) substantial amount of work to design and implement robustly, I'd guess. If you're keen to propose a design, please jump in, but I can't see myself tacking this in the immediate future.

Since this repo is being wound down in favor of https://github.com/serilog/serilog-sinks-console, let's close the issue here and open a new one if someone's keen to take on the work.

Cheers!
