### ISSUE TITLE
Source for release of 2.0.0

### ISSUE THREAD

**Issue by bjoernbusch** [serilog/serilog-sinks-coloredconsole#14]
For software clearing purposes I would require the sources for the 2.0.0. release, are they available somewhere or do we have to upgrade to 3.0.0.?

Thanks!

**Comment by nblumhardt** [comment]
Hi Bjoern, thanks for getting in touch. They're in this Git repository - here's the last commit from the 2.0 line:

https://github.com/serilog/serilog-sinks-coloredconsole/tree/a1049bdb9daf2a9ab703277bead6e80da7cfb469

Hope this helps,
Nick

**Comment by nblumhardt** [comment]
Assuming you were able to track this down. Let me know if you still need help.

**Comment by bjoernbusch** [comment]
Thanks for the link. It was easier to just upgrade this and other packages to a more recent version where the release was made in GitHub.
