### ISSUE TITLE
Update for .NET Core RC2

### ISSUE THREAD

**Issue by jeremymeng** [serilog/serilog-sinks-coloredconsole#2]
Would you mind if I submit a PR for RC2 update?  If yes, is it supposed to be a `dev` branch to submit against, or just directly to `master` branch?  Most of the changes would be similar to RC2 updates of other sinks.

**Comment by merbla** [comment]
Thanks @jeremymeng that would be fantastic!

The [console sink](https://github.com/serilog/serilog-sinks-console) might be a good template for the changes.
